name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run:
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{
          secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image for Backend
        run: docker build -t polstrat/nodejs-backend .

      - name: Publish image to Docker Hub
        run: docker push polstrat/nodejs-backend:latest




  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from Docker Hub
        run: docker pull polstrat/nodejs-backend:latest

      - name: Stop and Remove Old Container
        run: docker stop nodejsContainer && docker rm nodejsContainer || true

      - name: Run Docker Container for Backend
        run:
          docker run -d -p 8100:8100 --name nodejsContainer
          polstrat/nodejs-backend:latest

